name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare new release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip xfoxess dir
        run: |
          pwd
          ls -l /home/runner/work
          cd /home/runner/work/HA-FoxESS/HA-FoxESS/custom_components/sfoxess
          pwd
          zip sfoxess-${{ github.ref }}.zip -r ./
          ls -l /home/runner/work/HA-FoxESS/HA-FoxESS/custom_components/sfoxess
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/HA-FoxESS/HA-FoxESS/custom_components/sfoxess/sfoxess.zip
          asset_name: sfoxess-${{ github.ref }}.zip
          tag: ${{ github.ref }}
          overwrite: true