name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare new release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip xfoxess dir
        run: |
          cd /home/runner/work/HA-FoxESS/HA-FoxESS/custom_components/sfoxess
          zip sfoxess.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/HA-FoxESS/HA-FoxESS/custom_components/sfoxess/sfoxess.zip
          asset_name: sfoxess.zip
          tag: ${{ github.ref }}
          overwrite: true